services:
  golang-migrate-run:
    image: migrate/migrate
    command: -path=/migrations/ -database postgres://mdblog:mdblog@db_run/mdblog?sslmode=disable up
    volumes:
      - ../db:/migrations
    depends_on:
      db_run:
        condition: service_healthy
  db_run:
    image: postgres
    environment:
      - POSTGRES_USER=mdblog
      - POSTGRES_PASSWORD=mdblog
      - POSTGRES_DB=mdblog
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mdblog"]
      interval: 5s
      timeout: 5s
      retries: 5