services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mdblog
      - POSTGRES_PASSWORD=mdblog
      - POSTGRES_DB=mdblog
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mdblog" ]
      interval: 5s
      timeout: 5s
      retries: 5
  golang-migrate-run:
    image: migrate/migrate
    command: -path=/migrations/ -database postgres://mdblog:mdblog@db/mdblog?sslmode=disable up
    volumes:
      - ../be/db:/migrations
    depends_on:
      db:
        condition: service_healthy
  backend:
    build:
      context: ../be
      dockerfile: ../be/docker/local.Dockerfile
      no_cache: true
    environment:
      SERVER_ADDRESS: 0.0.0.0:8080
      DATABASE_URL: 'postgres://mdblog:mdblog@db:5432/mdblog?sslmode=disable'
    ports:
      - '8080:8080'
    depends_on:
      golang-migrate-run:
        condition: service_completed_successfully
  frontend:
    build:
      context: ../fe
      dockerfile: docker/Dockerfile
    ports:
      - '3000:8080'
    depends_on:
      backend:
        condition: service_started
