[server]
address = ":0"

[database]
url = "postgres://mdblog:mdblog@localhost:5431/mdblog?sslmode=disable"
maxConn = 5

[cors]
allowedOrigins = "http://localhost:3000"

[auth]
jwksUrl = "https://dev-ut2ynj113s1o5lxz.us.auth0.com/.well-known/jwks.json"