name: Markdown Blog -  lint and build
on:
  pull_request:
    branches:
      - master
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          npm i -g @commitlint/{cli,config-conventional}
          echo "export default { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
          echo "$TITLE" | commitlint
        env:
          TITLE: ${{ github.event.pull_request.title }}
        name: Verify Pull Request Title
      - uses: actions/checkout@v4
      - name: Determine impacted paths
        id: path_filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            openapi:
             - 'openapi/**'
        if: steps.path_filter.outputs.openapi == 'true'
      - run: |
          cd openapi
          npm ci
          npm run test
          npm run build
        name: Test & Build - Node
        if: steps.path_filter.outputs.openapi == 'true'
