name: Common - Pull Request Title - compliance check
on:
  pull_request:
    branches:
      - master
jobs:
  pr-title-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          npm i -g @commitlint/{cli,config-conventional}
          echo "export default { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
          echo "$TITLE" | commitlint
        env:
          TITLE: ${{ github.event.pull_request.title }}
        name: Verify Pull Request Title